name: Melon Ticket Watcher
on:
  # 이 부분을 추가하면 수동으로 실행할 수 있는 버튼이 생깁니다.
  workflow_dispatch:

  schedule:
    # 1분마다 실행
    - cron: '*/1 * * * *'

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          # 제공해주신 공연 ID로 수정했습니다.
          product-id: 211942

          # 'time-id'를 'schedule-id'로 수정하고, 제공해주신 ID를 입력했습니다.
          # scheduleNoArray 값이 바로 schedule-id 입니다.
          schedule-id: 100058

          # 'grade-id'를 'seat-id'로 수정했습니다. (기본값 1_0)
          # 원하는 좌석 등급이 따로 있다면 이 값을 변경해야 합니다.
          seat-id: 1_0
          
          # [마지막 시도] Referer 정보를 추가하여 실제 사용자인 것처럼 위장합니다.
          args: '-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -H "Referer: https://ticket.melon.com/"'

          # 슬랙 알림 설정 (이 부분은 수정하지 않아도 됩니다)
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '<!channel> 티켓 발견! 지금 바로 예매하세요!'
